package com.aikocraft.raytracer.input;

import com.aikocraft.raytracer.Game;

public class Input {

	public static final int K_ENTER = '\n';
	public static final int K_BACK_SPACE = '\b';
	public static final int K_TAB = '\t';
	public static final int K_CANCEL = 0x03;
	public static final int K_CLEAR = 0x0C;
	public static final int K_SHIFT = 0x10;
	public static final int K_CONTROL = 0x11;
	public static final int K_ALT = 0x12;
	public static final int K_PAUSE = 0x13;
	public static final int K_CAPS_LOCK = 0x14;
	public static final int K_ESCAPE = 0x1B;
	public static final int K_SPACE = 0x20;
	public static final int K_PAGE_UP = 0x21;
	public static final int K_PAGE_DOWN = 0x22;
	public static final int K_END = 0x23;
	public static final int K_HOME = 0x24;
	public static final int K_LEFT = 0x25;
	public static final int K_UP = 0x26;
	public static final int K_RIGHT = 0x27;
	public static final int K_DOWN = 0x28;
	public static final int K_COMMA = 0x2C;
	public static final int K_MINUS = 0x2D;
	public static final int K_PERIOD = 0x2E;
	public static final int K_SLASH = 0x2F;
	public static final int K_0 = 0x30;
	public static final int K_1 = 0x31;
	public static final int K_2 = 0x32;
	public static final int K_3 = 0x33;
	public static final int K_4 = 0x34;
	public static final int K_5 = 0x35;
	public static final int K_6 = 0x36;
	public static final int K_7 = 0x37;
	public static final int K_8 = 0x38;
	public static final int K_9 = 0x39;
	public static final int K_SEMICOLON = 0x3B;
	public static final int K_EQUALS = 0x3D;
	public static final int K_A = 0x41;
	public static final int K_B = 0x42;
	public static final int K_C = 0x43;
	public static final int K_D = 0x44;
	public static final int K_E = 0x45;
	public static final int K_F = 0x46;
	public static final int K_G = 0x47;
	public static final int K_H = 0x48;
	public static final int K_I = 0x49;
	public static final int K_J = 0x4A;
	public static final int K_K = 0x4B;
	public static final int K_L = 0x4C;
	public static final int K_M = 0x4D;
	public static final int K_N = 0x4E;
	public static final int K_O = 0x4F;
	public static final int K_P = 0x50;
	public static final int K_Q = 0x51;
	public static final int K_R = 0x52;
	public static final int K_S = 0x53;
	public static final int K_T = 0x54;
	public static final int K_U = 0x55;
	public static final int K_V = 0x56;
	public static final int K_W = 0x57;
	public static final int K_X = 0x58;
	public static final int K_Y = 0x59;
	public static final int K_Z = 0x5A;
	public static final int K_OPEN_BRACKET = 0x5B;
	public static final int K_BACK_SLASH = 0x5C;
	public static final int K_CLOSE_BRACKET = 0x5D;
	public static final int K_NUMPAD0 = 0x60;
	public static final int K_NUMPAD1 = 0x61;
	public static final int K_NUMPAD2 = 0x62;
	public static final int K_NUMPAD3 = 0x63;
	public static final int K_NUMPAD4 = 0x64;
	public static final int K_NUMPAD5 = 0x65;
	public static final int K_NUMPAD6 = 0x66;
	public static final int K_NUMPAD7 = 0x67;
	public static final int K_NUMPAD8 = 0x68;
	public static final int K_NUMPAD9 = 0x69;
	public static final int K_MULTIPLY = 0x6A;
	public static final int K_ADD = 0x6B;
	public static final int K_SEPARATER = 0x6C;
	public static final int K_SEPARATOR = K_SEPARATER;
	public static final int K_SUBTRACT = 0x6D;
	public static final int K_DECIMAL = 0x6E;
	public static final int K_DIVIDE = 0x6F;
	public static final int K_DELETE = 0x7F; /* ASCII DEL */
	public static final int K_NUM_LOCK = 0x90;
	public static final int K_SCROLL_LOCK = 0x91;
	public static final int K_F1 = 0x70;
	public static final int K_F2 = 0x71;
	public static final int K_F3 = 0x72;
	public static final int K_F4 = 0x73;
	public static final int K_F5 = 0x74;
	public static final int K_F6 = 0x75;
	public static final int K_F7 = 0x76;
	public static final int K_F8 = 0x77;
	public static final int K_F9 = 0x78;
	public static final int K_F10 = 0x79;
	public static final int K_F11 = 0x7A;
	public static final int K_F12 = 0x7B;

	public static boolean getKey(int key) {
		return Game.i.im.keys[key];
	}
}
